<?php

namespace Guest\BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        return $this->createQueryBuilder('u');
    }

    public function getManager()
    {
        return $this->getEntityManager();
    }

    public function findByEmail($email = '')
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.email LIKE :email')
            ->setParameter('email', $email)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
