imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    bundles: [ AcmeHomeWorkBundle ]
    use_controller: true
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        # jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        # jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
            output: css/bootstrap.css
        bootstrap_min_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
            filters:
                - cssrewrite
            output: css/bootstrap.min.css
        starter_template_css:
            inputs:
                - %kernel.root_dir%/../src/Acme/HomeWorkBundle/Resources/public/css/starter-template.css
            output: css/starter-template.css
        bootstrap_theme_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css
            output: css/bootstrap-theme.min.css
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
            output: js/jquery.js
        javaScript_bootstrap:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
            output: js/bootstrap.min.js

#swiftmailer:
#    delivery_address: me@example.com
