<?php

namespace Guest\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        return $this->createQueryBuilder('a')->orderBy('a.id', 'ASC');
    }

    public function getManager()
    {
        return $this->getEntityManager();
    }
}
