<?php

namespace Guest\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        return $this->createQueryBuilder('u');
    }

    public function getManager()
    {
        return $this->getEntityManager();
    }
}
