_article:
    path:   /article
    defaults: { _controller: AcmeDemoBundle:Article:index }

_article_view:
    path:  /article/view
    defaults: { _controller: AcmeDemoBundle:Article:view }

_article_edit:
    path:  /article/edit
    defaults: { _controller: AcmeDemoBundle:Article:edit }