_article:
    path:   /article
    defaults: { _controller: AcmeDemoBundle:Article:index }

_article_about:
    path:  /article/about
    defaults: { _controller: AcmeDemoBundle:Article:about }

_article_contact:
    path:  /article/contact
    defaults: { _controller: AcmeDemoBundle:Article:contact }