<?php

namespace Acme\HomeWorkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByNick($nick = '')
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.nick LIKE :nick')
            ->setParameter('nick', $nick)
            ->getQuery();

        return $query->getSingleResult();
    }
}
