_article_welcome:
    path:   /{page}
    defaults: { _controller: GuestBookBundle:Home:index, page:1 }

_user:
    path:  /user/{id}/{page}
    defaults: { _controller: GuestBookBundle:User:index, page:1 }
    requirements:
          id:  \d+

_article:
    path:  /article/{id}
    defaults: { _controller: GuestBookBundle:Article:index }
    requirements:
          id:  \d+

_not_found:
    path: /404
    defaults: { _controller: GuestBookBundle:Default:notFound }

_article_remove:
    path:  /article/{id}/remove
    defaults: { _controller: GuestBookBundle:Article:remove }
    requirements:
          id:  \d+

_article_update:
    path:  /article/{id}/update
    defaults: { _controller: GuestBookBundle:Article:update }
    requirements:
          id:  \d+