_article:
    path:   /
    defaults: { _controller: AcmeHomeWorkBundle:Article:index }

_article_about:
    path:  /about
    defaults: { _controller: AcmeHomeWorkBundle:Article:about }

_article_contact:
    path:  /contact
    defaults: { _controller: AcmeHomeWorkBundle:Article:contact }

_user:
    path:  /user
    defaults: { _controller: AcmeHomeWorkBundle:Article:user }