_article_welcome:
    path:   /
    defaults: { _controller: AcmeHomeWorkBundle:Article:index }

_user:
    path:  /user/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Article:user }
    requirements:
          id:  \d+

_category:
    path:  /category/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Article:category }
    requirements:
          id:  \d+

_article:
    path:  /article/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Article:article }
    requirements:
          id:  \d+