_article_welcome:
    path:   /
    defaults: { _controller: AcmeHomeWorkBundle:Home:index }

_user:
    path:  /user/{id}
    defaults: { _controller: AcmeHomeWorkBundle:User:index }
    requirements:
          id:  \d+

_user_forgot:
    path:  /user/forgot/{id}
    defaults: { _controller: AcmeHomeWorkBundle:User:forgotData }
    requirements:
          id:  \d+

_category:
    path:  /category/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Category:index }
    requirements:
          id:  \d+

_article:
    path:  /article/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Article:index }
    requirements:
          id:  \d+

_tag:
    path:  /tag/{id}
    defaults: { _controller: AcmeHomeWorkBundle:Tag:index }
    requirements:
          id:  \d+